<FirstScreen>:
    GridLayout:
        cols: 1
        padding: 10
        spacing: 10
        Image:
            id: img
            size_hint_y: 0.7
        TextInput:
            id: user_query
            size_hint_y: 0.2
        Button:
            text: 'Search Image'
            size_hint_y: 0.1
            on_press: root.search_image()


<RootWidget>:
    FirstScreen:
        id: screen_t
        name: 'screen_t'